### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "suyeon@email.com",
    "password": "suyeon123"
}

### Sign in
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "test"
}

### Sign out
POST http://localhost:3000/auth/signout

{
    "email": "test@gmail.com",
    "password": "test"
}

###  Get the currently signed-in user
GET http://localhost:3000/auth/whoami

###  Find an user by id
GET http://localhost:3000/auth/4

###  Find all users by email
GET http://localhost:3000/auth?email=hanna@gmail.com

###  Delete user by id
DELETE http://localhost:3000/auth/4

### Update an user 
PATCH http://localhost:3000/auth/4
Content-Type: application/json

{
    "email": "suyeon@gmail.com"
}